# Generated by Django 4.1.4 on 2023-01-06 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Department Table',
            },
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, null=True)),
                ('employee_level', models.CharField(choices=[('Genin', 'Genin'), ('Chunin', 'Chunin'), ('Jonin', 'Jonin')], default='Genin', max_length=20)),
                ('employee_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appemployee.departmentmodel')),
            ],
            options={
                'verbose_name': 'Employee Table',
            },
        ),
    ]
